### ISSUE TITLE
Make file names as default for scoring

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#12]
Tool currently requires --filepath for input SBOM
`      --filepath string   sbom file path
`      
 Let's make that default so that we can get this done
 
 build/sbomqs score ~/sbom-samples/repos/trivy-bom.spdx
 
 without `--filepath`

**Comment by riteshnoronha** [comment]
@kchetans i finally read the cobra documentation and understood how to fix this. Essentially my implementation is incorrect. I have mixed the concept of flags and args. I will take this task up after my json change. 

You can close your existing branch.
