### ISSUE TITLE
Tool does not report correct number of components for nested CycloneDX SBOMs

### ISSUE THREAD

**Issue by schlenk** [interlynk-io/sbomqs#133]
The tool seems to not traverse the component graph properly, see for example:

```
sbomqs.exe score bom_issue_328_components.json
SBOM Quality Score:5.9  components:2    bom_issue_328_components.json
```

The SBOM obviously has 4 components described. 1 component in the BOM metadata and three libraries A, B, C.
 
Using the simple test case file from:

https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/tests/fixtures/json/1.4/bom_issue_328_components.json

**Comment by riteshnoronha** [comment]
Let me take a look will get back.

**Comment by riteshnoronha** [comment]
OK we have a fix here https://github.com/interlynk-io/sbomqs/pull/134,  should be part of our next release, if u would like to use it earlier, let me know.

**Comment by riteshnoronha** [comment]
A new version of the tool v0.0.13 has been released.
