### ISSUE TITLE
configpath and feature flags do not filter

### ISSUE THREAD

**Issue by mattymo30** [interlynk-io/sbomqs#139]
Hello,

I was trying to score an sbom using a modified features.yaml file. However, none of the categories or criteria would be ignored when I set enabled to false.

Also, when I try to run the -f or --filter command with a feature string, nothing happens and it defaults to the default output with all features.

I downloaded sbomqs using Go Install with v0.0.13 on a Windows/amd64 platform.

Currently, I have tried these two flags with the sample files provided with the tool.

**Comment by riteshnoronha** [comment]
@mattymo30 thanks for informing me, I am working on a fix for this issue, should be in the v0.0.14. May i ask what is your usecase.

**Comment by mattymo30** [comment]
@riteshnoronha Hello,

I have been testing with the samples files the tools provides in the samples folder.

In the features.yaml file, I have made several criteria and categories set to false for enabled. It was more to understand how the flags work and how to customize the scoring through the file.

This is similar to my usage of the -f flag, I was learning how to use this tool with the several sample files provided.

Both just default to the default output for scoring, even when I enter a valid configpath or feature.

**Comment by riteshnoronha** [comment]
@mattymo30 yes this feature broke when i made somechanges in v0.0.10. I will be fixing this for v0.0.14. Will msg you when it starts working. Let me know if this is blocking any work for u, i can expedite the fix.

**Comment by mattymo30** [comment]
@riteshnoronha No rush! Thank you!

**Comment by riteshnoronha** [comment]
@mattymo30 v0.0.14 has been released, it should work now. Let me know if you find any more issues.

**Comment by mattymo30** [comment]
@riteshnoronha Thank you!
