### ISSUE TITLE
Integrate with DT

### ISSUE THREAD

**Issue by riteshnoronha** [interlynk-io/sbomqs#144]
Integrated with Dependency Track, and we should be able to score projects.

**Comment by surendrapathak** [comment]
DT Integrated solution will have the following features:

1. Pull and quality score SBOM from the Dependency Track (assume API configuration provided)
2. [Optional] Update the score as a tag on the project page:
<img width="327" alt="Screenshot 2023-05-05 at 9 56 34 AM" src="https://user-images.githubusercontent.com/1686327/236520145-c235a477-aec9-4d7d-b686-3b103a502259.png">
