### ISSUE TITLE
Provide ability to run the tool in air-gap environment

### ISSUE THREAD

**Issue by pushkargr** [interlynk-io/sbomqs#155]
Issue:
Currently I'm facing the issue with the tool where it tries to check for the latest version every time it runs and as I'm trying to process a lot of documents I'm hitting GitHub rate limits.

> panic: GET https://api.github.com/repos/interlynk-io/sbomqs/releases/latest: 403 API rate limit exceeded for 208.85.208.87. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 4m40s]
goroutine 1 [running]:
github.com/interlynk-io/sbomqs/cmd.checkIfLatestRelease()
	github.com/interlynk-io/sbomqs@v0.0.16/cmd/root.go:59 +0x1e6
github.com/interlynk-io/sbomqs/cmd.Execute()
	github.com/interlynk-io/sbomqs@v0.0.16/cmd/root.go:40 +0x19
main.main()
	github.com/interlynk-io/sbomqs@v0.0.16/main.go:20 +0x17

Suggestion:
Access to internet should be optional and not per-enabled and tool should be able to adapt to that.

**Comment by riteshnoronha** [comment]
@pushkargr run it with INTERLYNK_DISABLE_VERSION_CHECK=true, let me know if it works

**Comment by riteshnoronha** [comment]
i will add it to the readme

**Comment by riteshnoronha** [comment]
@pushkargr closing this out as there is a way to run it airgap env. Let me know if a better soln is required.

**Comment by riteshnoronha** [comment]
Added a link to our readme too https://github.com/interlynk-io/sbomqs#quality-score-in-an-airgapped-environment
