### ISSUE TITLE
Add support for component types

### ISSUE THREAD

**Issue by riteshnoronha** [interlynk-io/sbomqs#164]
This is to enhance component validation to ensure:
1. [CycloneDX](https://cyclonedx.org/docs/1.5/json/#components_items_type) - Each component has a type of permitted enum
2. [SPDX](https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field) - Each component/file has a primary purpose of permitted enum

**Comment by surendrapathak** [comment]
Fixed
