### ISSUE TITLE
sbomqs version has unnecessary detail

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#17]
The attached result of `sbomqs version` shows GitCommit and GitTreeStatus, which are unnecessary for the official release and can be omitted.

<img width="520" alt="Screenshot 2023-02-07 at 10 33 33 PM" src="https://user-images.githubusercontent.com/1686327/217455599-5407950f-8305-4ed6-9a9a-a55f3971a356.png">

**Comment by kchetans** [comment]
default feature of used package no-change
