### ISSUE TITLE
SPDX Creator Name may include spaces in the tool name

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#180]
References: 
1. https://github.com/interlynk-io/sbombenchmark.dev/issues/11
2. https://github.com/spdx/tools-python/blob/1ecc6f669da939d8b4f213f0a49cc0a78578c16b/src/spdx_tools/spdx/parser/actor_parser.py#L16

**Comment by sschuberth** [comment]
I agree that the SPDX spec (again) is not very clear here. The [JSON spec](https://github.com/spdx/spdx-spec/blob/v2.2.1-ISO-final/schemas/spdx-schema.json#L196-L204) just says "If the SPDX file was created using a software tool, indicate the name and version for that tool.", but the example in the [Markdown spec](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field) suggests a `Tool: toolidentifier-version` syntax.

**Comment by sschuberth** [comment]
To be on the safe side, I've [created a PR for ORT](https://github.com/oss-review-toolkit/ort/pull/7410) to use just "ort" instead of "OSS Review Toolkit" as the tool name (and also no spaces around `-` to separate the version).

**Comment by riteshnoronha** [comment]
@sschuberth we have made the changes for the toolname and version rule to be more accommodating. v0.0.20 has been released.
