### ISSUE TITLE
Doesn't work with CycloneDX 1.5

### ISSUE THREAD

**Issue by anthonyharrison** [interlynk-io/sbomqs#202]
Attempt to score a CyclonDX SBOM (version 1.5) results in the following error message

`failed to parse /tmp/javascript.json : json: cannot unmarshal object into Go struct field Metadata.metadata.tools of type []cyclonedx.Tool`

Problem is probably in the CycloneDX Go library

**Comment by riteshnoronha** [comment]
@anthonyharrison  we currently dont support cyclonedx 1.5. Although we have plans to support once adoption increases. If you have a cyclondx1.5 sbom and willing to share it, we can use it for testing.

**Comment by riteshnoronha** [comment]
v0.0.29 fixes this.
