### ISSUE TITLE
CycloneDX 1.5 is not considered a valid spec

### ISSUE THREAD

**Issue by riteshnoronha** [interlynk-io/sbomqs#213]
CycloneDX 1.5 is not considered a valid spec. Needs to be added as a supported spec.

**Comment by deepharness** [comment]
Do we have a timeline when CycloneDx 1.5 will be supported ?

**Comment by riteshnoronha** [comment]
It should be supported currently. I forgot to update this issue. You facing any issue?

**Comment by riteshnoronha** [comment]
Supported in version 0.0.30. closing.

**Comment by deepharness** [comment]
> It should be supported currently. I forgot to update this issue. You facing any issue?

Thanks , I just verified in 0.0.30 its working

**Comment by riteshnoronha** [comment]
@deepharness happy to see you are using the tool. Do let us know if you would like any particular features or improvements.
