### ISSUE TITLE
Invalid reportFormat must result in help message #23

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#22]
Acual:
<img width="593" alt="Screenshot 2023-02-10 at 11 29 32 AM" src="https://user-images.githubusercontent.com/1686327/218180596-aba30ef6-7c84-426f-9f1a-50fa3300908b.png">

Expected:
1. error in reportFormat value ('custom') should be reported with a help message
2. Exit code should not be 0

**Comment by riteshnoronha** [comment]
Fixed in v0.0.7
