### ISSUE TITLE
Please remove cdxgen from sbombenchmark.dev

### ISSUE THREAD

**Issue by prabhu** [interlynk-io/sbomqs#225]
CPE is a dated imprecise identifiers for Products. Purls on the other hand is for packages and much more precise. All this tool does is to simply check if the CPE field is non-empty. Tools like Syft etc, simply make up a random CPE to improve the NTIA score.

https://github.com/interlynk-io/sbomqs/blob/ca4f441fc9a84cafb129c8d1570afb32029c3df7/pkg/cpe/cpe.go#L26

Either this project needs to change to truly validate CPE against the dictionary from NVD, or remove cdxgen which will never include CPE (that too a made up one) in the generated SBOM.

**Comment by surendrapathak** [comment]
Thanks for reporting this, @prabhu. I agree that a valid CPE vs purely generated CPE can be a challenge regarding how the rules are written. As we are hard-pressed on CRA support, please give us a few days to think over it, and if we cannot come up with a fair way to address CDXgen's unique concerns, we'll remove it from SBBM.

**Comment by surendrapathak** [comment]
Hi @prabhu  - While there are challenges with getting the right CPE, as there is no fully reliable transition plan from CPE to PURL yet, both [SPDX 3](https://spdx.github.io/spdx-spec/v3.0/model/Core/Vocabularies/ExternalIdentifierType/) and [CDX 1.6](https://cyclonedx.org/docs/1.6/json/#components_items_cpe) continue to treat CPE as a first-class citizen.

Therefore, identifying missing identifiers is an important step in evaluating what SBOM capabilities are useful.

Of course, as the organizational needs change, there has been a need to [customize](https://github.com/interlynk-io/sbomqs?tab=readme-ov-file#goal-3-customizable-output) to specific rules, and sbomqs comes ready with that option

We are tuned to if we will find a single reliable ID and will make changes once that happens. But in the meantime, if you continue to believe cdxgen should opt-out, we can make that changes this weekend. Please let us know.

**Comment by prabhu** [comment]
Please do. Thank you!

**Comment by surendrapathak** [comment]
Sure! It's been deployed.
