### ISSUE TITLE
Invalid category must result in help message

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#23]
Same as #22 for category

Actual:
<img width="842" alt="Screenshot 2023-02-10 at 11 49 08 AM" src="https://user-images.githubusercontent.com/1686327/218184518-84bcc556-88ea-40c8-8803-4f8a330509f6.png">

Expected:
error in category value ('NTIA-minimum-element') should be reported with a help message
The exit code should not be 0

**Comment by riteshnoronha** [comment]
fixed in v0.0.7
