### ISSUE TITLE
Should be able to score SBOM found at a URL path. 

### ISSUE THREAD

**Issue by riteshnoronha** [interlynk-io/sbomqs#266]
Add support for sbomqs to read sboms present in the url.

**Comment by viveksahu26** [comment]
Hey  @riteshnoronha , for now I am adding support for only git URLs. As mostly examples SBOMs are present in some git reposirory. For example: https://github.com/interlynk-io/sbomqs/blob/main/samples/sbomqs-spdx-syft.json . WDT ?
