### ISSUE TITLE
[CLI] Enhance `sbomqs score` command output with color-coded scores

### ISSUE THREAD

**Issue by viveksahu26** [interlynk-io/sbomqs#302]
## Description
Currently, the output of the sbomqs score command displays all scores in the same color (white), regardless of whether the score is full or zero. This makes it difficult to quickly identify elements that are missing or need improvement. For example:

![image](https://github.com/user-attachments/assets/cf018c3c-3e64-41b8-bd86-bb7770e327f1)

However, when there are elements with a score of 0.0, they are not emphasized or not grabbing attention of the user which needs improvement.

## Solution
Implementing color-coded(red color) output will make it easier for users to quickly identify areas that need attention and improvement. This visual enhancement will improve the overall user experience and usability of the sbomqs score command.

**Comment by viveksahu26** [comment]
hey @riteshnoronha , your thoughts on this ?

**Comment by riteshnoronha** [comment]
Yes good idea.
