### ISSUE TITLE
Create signed releases

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#31]
Reference: Signing releases on GitHub
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by kchetans** [comment]
### Git sign

1. setup gpg localy and git https://docs.github.com/en/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key
2. Go to git account and enabled Vigilant mode
 https://github.com/settings/keys

3. Enable mandatory sign contributes on protected branch (Enabled Require signed commits
Commits pushed to matching branches must have verified signatures.)
 
4. Sign commit commands https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
5. Sign Tags commands https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-tags

**Comment by riteshnoronha** [comment]
@kchetans Both me & surendra have enabled signed commits. Please enable it for you too, then we can close this issue.

**Comment by riteshnoronha** [comment]
Looks like everyone is using signed commits now, we can close this
