### ISSUE TITLE
Framing Third Edition Compliance Checks

### ISSUE THREAD

**Issue by surendrapathak** [interlynk-io/sbomqs#313]
CISA' [Framing Document Third Edition](https://docs.google.com/document/d/1uddfhPqflTOeYK7ZJjS4gGa8pspwez6mhJUjTrvu4J4/edit) is under community review and suggests SBOM field's described as
- Minimum Expected
- Recommended Practice
- Aspirational Goal

sbomqs should aim to
- identify Minimum Expected fields
- elevate result to 'Recommended Practice' when SBOM alone can confirm that (e.g. Relationship is present for all components)
- elevate result to 'Aspirational Goal' when SBOM alone can confirm that (e.g. Component license all details are included)

The result should be accessible as JSON to meet requirements discussed in https://github.com/CISA-SBOM-Community/SBOM-Generation/issues/19

**Comment by viveksahu26** [comment]
This table will illustrate the summary of this draft in table format:

| **Attribute**           | **Requirement Level** | **Minimum Requirement**                                                                                                    | **Recommended Practice**                                                                                     | **Aspirational Goal**                                                                | **CycloneDX** | **SPDX** | **sbomqs** |
|-------------------------|-----------------------|-----------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|---------------|----------|------------|
| **Author Name**         | Must                  | List all SBOM creators. Author may different from Supplier Name.                                                                       | Include tools/versions used in SBOM creation.                                                                 |                                                                                     |  ✔️ ([metadata->tools](https://cyclonedx.org/docs/1.6/json/#metadata_tools_oneOf_i0_components), [metadata->authors](https://cyclonedx.org/docs/1.6/json/#metadata_authors)), [metadata->manufacturer](https://cyclonedx.org/docs/1.6/json/#metadata_manufacturer)  | ✔️ ([CreationInfo->Creator](https://spdx.github.io/spdx-spec/v2.2.2/document-creation-information/#68-creator-field) )      | ✔️ (NTIA category - `sbom_authors`)         |
| **Timestamp**           | Must                  | Date and time SBOM was created (e.g., 2024-05-23T13:51:37Z).                                                                |                                                                                                               |                                                                                     | ✔️ ([metadata->timestamp](https://cyclonedx.org/docs/1.6/json/#metadata_timestamp)	) | ✔️ ([CreationInfo->created](https://spdx.github.io/spdx-spec/v2.2.2/document-creation-information/#69-created-field))      | ✔️ (NTIA Category - `sbom_creation_timestamp`)          |
| **Type**                | Optional              |                                                                           |                                                                                                               | Provide context for how and why the SBOM was created.                                                   | ✔️ ([metadata->component->type](https://cyclonedx.org/docs/1.6/json/#metadata_component_type))           | ✔️ (?)      | ✔️ (Confirm this) |
| **Primary Component**   | Must                  | Identifies the root component of dependencies.                                                                              |                                                                                                               |                                                                                     | ✔️  ([metadata->component](https://cyclonedx.org/docs/1.6/json/#metadata_component))          | ✔️ (?)      | ✔️ (Quality Category - `sbom_with_primary_component`)          |
| **Component Name**      | Must                  | Public name of component by supplier/creator.                                                                                            |                                                                                                               |                                                                                     | ✔️ ([component->name](https://cyclonedx.org/docs/1.6/json/#components_items_name)	)          | ✔️ ([package->name](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#71-package-name-field)	)  | ✔️ (NTIA Category - `comp_with_name`)         |
| **Version**             | Must                  | Specifies software iteration (e.g., `1.0.0`).                                                                               |                                                                                                               |                                                                                     | ✔️  ([component->version](https://cyclonedx.org/docs/1.6/json/#components_items_version)	)          | ✔️ ([package->versionInfo](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#73-package-version-field))      | ✔️  (NTIA Category - `comp_with_version`)        |
| **Supplier Name**       | Must                  | Entity that created the component.                                                                                          |                                                                                                               |                                                                                     | ✔️  ([component->manufacturer](https://cyclonedx.org/docs/1.6/json/#components_items_manufacturer), [component->authors](https://cyclonedx.org/docs/1.6/json/#components_items_authors), and maybe [component->supplier](https://cyclonedx.org/docs/1.6/json/#components_items_supplier), )   | ✔️  ([package->supplier](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#75-package-supplier-field), [package->originator](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#76-package-originator-field))  | ✔️ (NTIA Category - `comp_with_supplier`) |
| **Unique Identifier**   | Must                  | Unique identifier (e.g., CPE, PURL, UUID).                                                                                  |                                                                                                               |                                                                                     | ✔️ ([component->cpe](https://cyclonedx.org/docs/1.6/json/#components_items_cpe), [component->purl](https://cyclonedx.org/docs/1.6/json/#components_items_purl), [component->omniborId](https://cyclonedx.org/docs/1.6/json/#components_items_omniborId), [component->swhid](https://cyclonedx.org/docs/1.6/json/#components_items_swhid), [component->swid](https://cyclonedx.org/docs/1.6/json/#components_items_swid)	)   | ✔️  ([package->externalRef](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#721-external-reference-field)	)   | ✔️  (NTIA Category - `comp_with_uniq_ids` )     |
| **Cryptographic Hash**  | Must                  | Hash for the compiled binary (e.g., SHA-256).                                                                               | Hash for the Primary Component using secure algorithms.                                                       |                                                                                     | ✔️ ([component->hashes](https://cyclonedx.org/docs/1.6/json/#components_items_hashes)	)  | ✔️ ([package->checksum](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#710-package-checksum-field)	) | ✔️ (Semantic Category `comp_with_checksums` )         |
| **Relationship**        | Must                  | Declare relationships between the primary component and direct dependencies. --> `composition`                                                | Declare relationships for all components listed. --> `dependencies` | List all dependencies, included or not.  | ✔️  ([dependencies](https://cyclonedx.org/docs/1.6/json/#dependencies), [compositions](https://cyclonedx.org/docs/1.6/json/#compositions)         | ✔️ ([relationships](https://spdx.github.io/spdx-spec/v2.2.2/relationships-between-SPDX-elements/#111-relationship-field))       | ✔️ (sbomqs support in CRA and OCT compliance ) |
| **Relationship Assertions** | Optional        | Non-authoritative claims about components.                                                                                  | Make non-authoritative claims as needed.                                                                      |                                                                                     | ✔️ ( [dependencies](https://cyclonedx.org/docs/1.6/json/#dependencies), [compositions](https://cyclonedx.org/docs/1.6/json/#compositions)         | ✔️ ([relationships](https://spdx.github.io/spdx-spec/v2.2.2/relationships-between-SPDX-elements/#111-relationship-field))  	)   | ✔️  ([relationships](https://spdx.github.io/spdx-spec/v2.2.2/relationships-between-SPDX-elements/#111-relationship-field))  | ✔️  (sbomqs support in CRA and OCT compliance )       |
| **License**             | Optional              | Legal terms for software use, modification, and distribution.                                                               | Detailed license info for many components.                                                                    | Detailed license info for all components with attestation.                         | ✔️  ([component->licenses](https://cyclonedx.org/docs/1.6/json/#components_items_licenses)	)          | ✔️ ([Package->licenseConcluded](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#713-concluded-license-field), [Package->licenseDeclared](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#715-declared-license-field)	)   | ✔️ ( Semantic Category - `comp_with_licenses`)      |
| **Copyright Holder**    | Must                  | Copyright info for Primary Component.                                                                                       | Copyright info for other components where available.                                                          | Ensure copyright info for all components.                                           | ✔️   ([component->copyright](https://cyclonedx.org/docs/1.6/json/#components_items_copyright)	)         | ✔️  ([Package->copyrightText](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#717-copyright-text-field))     | ✔️ (supported in OCT Compliance report)          |

**Comment by viveksahu26** [comment]
@surendrapathak , we have almost all fields drafted in [3rd edition of minimum elements by NTIA](https://docs.google.com/document/d/1uddfhPqflTOeYK7ZJjS4gGa8pspwez6mhJUjTrvu4J4/edit?pli=1#heading=h.b3eh15cuhd8k). Like some of them are present in NTIA category, or Quality Category, etc or CRA/OCT compliance data fields, etc. Should we start working on implementation part of it ?
